// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjgedyauizpfudhekaud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZ2VkeWF1aXpwZnVkaGVrYXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NjU3ODEsImV4cCI6MjA3NjA0MTc4MX0.B-x1X5ayY5xvXQlAWyzOHe6I1rAjHRBrpekGHn_aWd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});